spring:
  cloud:
    # 服务注册和发现
    nacos:
      discovery:
        server-addr: local-ip:8848
  zipkin:
    base-url: http://local-ip:9411/
    sleuth:
      web:
        client:
          enabled: true
    sampler:
      # 抽样率，默认是0.1（90%的数据会被丢弃）
      probability: 0.5
