server:
  port: 9101
  use-forward-headers: true
  servlet:
    session:
      timeout: 86400s
      cookie:
        http-only: true
  compression:
    enabled: true
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain

spring:
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

  application:
    name: user-provider
  cloud:
    # 服务注册和发现
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  zipkin:
    base-url: http://127.0.0.1:9411/
    sleuth:
      web:
        client:
          enabled: true
    sampler:
      # 抽样率，默认是0.1（90%的数据会被丢弃）
      probability: 1.0

feign:
  sentinel:
    enabled: true
  httpclient:
    connection-timeout: 5000
    enabled: false
    max-connections: 200
    max-connections-per-route: 50
  okhttp:
    enabled: true

hystrix:
  threadpool:
    default:
      coreSize: 16 # 并发执行的最大线程数，默认10
      maxQueueSize: 100 # BlockingQueue的最大队列数，默认值-1
      queueSizeRejectionThreshold: 90 # 即使maxQueueSize没有达到，达到queueSizeRejectionThreshold值后，请求也会被拒绝，默认值5
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 5000

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
